---
- name: Copy MySQL file to server
  template: src=my.cnf.j2 dest=/home/vagrant/.my.cnf owner=vagrant group=vagrant mode=0600

- name: Start MySQL service
  service: name=mysql state=started

- name: Create my_app user
  mysql_user: name=my_app host=% password=secret priv=*.*:ALL state=present

- name: Create my_app database
  mysql_db: name=my_app state=present encoding=utf8
